"""CapCut-style FFmpeg look library: transitions, grades, motion, text, stills."""

from __future__ import annotations

# Official xfade transition names (FFmpeg) — 36+ CapCut-like wipes/dissolves
TRANSITION_LIBRARY: list[str] = [
    "fade",
    "fadeblack",
    "fadewhite",
    "fadegrays",
    "dissolve",
    "pixelize",
    "distance",
    "radial",
    "hblur",
    "wipeleft",
    "wiperight",
    "wipeup",
    "wipedown",
    "wipetl",
    "wipetr",
    "wipebl",
    "wipebr",
    "slideleft",
    "slideright",
    "slideup",
    "slidedown",
    "smoothleft",
    "smoothright",
    "smoothup",
    "smoothdown",
    "circlecrop",
    "rectcrop",
    "circleopen",
    "circleclose",
    "vertopen",
    "vertclose",
    "horzopen",
    "horzclose",
    "diagtl",
    "diagtr",
    "diagbl",
    "diagbr",
    "hlslice",
    "hrslice",
    "vuslice",
    "vdslice",
    "squeezeh",
    "squeezev",
    "zoomin",
]

# Color / film grades (25+)
EFFECT_FILTERS: dict[str, str] = {
    "none": "",
    "cinematic": "eq=contrast=1.08:saturation=1.12:brightness=0.02,vignette=PI/5.5",
    "vivid": "eq=contrast=1.14:saturation=1.28:brightness=0.03",
    "soft": "eq=contrast=0.96:saturation=0.92:brightness=0.04:gamma=1.05",
    "noir": "hue=s=0,eq=contrast=1.2:brightness=-0.02",
    "punch": "eq=contrast=1.18:saturation=1.22:brightness=0.05",
    "vignette": "vignette=PI/4.5,eq=contrast=1.06:saturation=1.08",
    "warm": "eq=contrast=1.06:saturation=1.1:gamma_r=1.05:gamma_b=0.95,colorbalance=rs=0.06:gs=0.02:bs=-0.04",
    "cool": "eq=contrast=1.05:saturation=1.05:gamma_b=1.08:gamma_r=0.95,colorbalance=rs=-0.04:bs=0.06",
    "teal_orange": "colorbalance=rs=0.08:gs=-0.02:bs=-0.06:rm=0.04:bm=-0.05,eq=contrast=1.1:saturation=1.15",
    "vintage": "eq=contrast=0.95:saturation=0.75:brightness=0.03:gamma=1.08,vignette=PI/4,noise=alls=8:allf=t",
    "bleach": "eq=contrast=1.25:saturation=0.55:brightness=0.08",
    "neon": "eq=contrast=1.2:saturation=1.45:brightness=0.04,unsharp=5:5:1.0:5:5:0.0",
    "pastel": "eq=contrast=0.92:saturation=0.85:brightness=0.06:gamma=1.1",
    "drama": "eq=contrast=1.22:saturation=0.95:brightness=-0.03,vignette=PI/4",
    "glow": "gblur=sigma=1.2,eq=contrast=1.05:saturation=1.12:brightness=0.04",
    "sharp": "unsharp=5:5:1.2:5:5:0.0,eq=contrast=1.08:saturation=1.05",
    "dream": "gblur=sigma=2.5,eq=saturation=1.15:brightness=0.05:gamma=1.08",
    "chrome": "eq=contrast=1.15:saturation=0.4:brightness=0.02",
    "sunset": "eq=gamma_r=1.12:gamma_g=1.02:gamma_b=0.88:saturation=1.18:contrast=1.06",
    "arctic": "eq=gamma_b=1.15:gamma_r=0.9:saturation=0.85:contrast=1.08:brightness=0.03",
    "ember": "eq=gamma_r=1.18:gamma_g=0.95:gamma_b=0.85:saturation=1.2:contrast=1.1",
    "matrix": "colorchannelmixer=rr=0.1:rg=0.7:rb=0.1:gr=0.05:gg=0.85:gb=0.1:br=0:bg=0.4:bb=0.2,eq=contrast=1.15",
    "retro_tv": "noise=alls=12:allf=t,eq=contrast=1.1:saturation=1.2,vignette=PI/3.5",
    "film_grain": "noise=alls=10:allf=t+u,eq=contrast=1.05:saturation=1.05",
    "high_key": "eq=brightness=0.12:contrast=0.92:saturation=1.05:gamma=1.12",
    "low_key": "eq=brightness=-0.08:contrast=1.2:saturation=0.9,vignette=PI/3.8",
    "sepia": "colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131,eq=contrast=1.05",
    "duo_pink": "colorchannelmixer=rr=0.9:rg=0.2:rb=0.3:gr=0.2:gg=0.5:gb=0.4:br=0.5:bg=0.2:bb=0.7,eq=contrast=1.08",
    "clarity": "unsharp=7:7:1.5:7:7:0.0,eq=contrast=1.1:saturation=1.08",
}

# Ken Burns / camera moves
MOTION_PRESETS: list[dict[str, str]] = [
    {
        "id": "punch_in",
        "zoom": "min(zoom+0.0028,1.28)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.14:saturation=1.22:brightness=0.04",
    },
    {
        "id": "slow_push",
        "zoom": "min(zoom+0.0012,1.18)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.06:saturation=1.1:brightness=0.02",
    },
    {
        "id": "rise",
        "zoom": "min(zoom+0.0015,1.2)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.52-(ih/zoom/2)-on*0.35",
        "eq": "eq=contrast=1.08:saturation=1.12:brightness=0.025",
    },
    {
        "id": "drift_left",
        "zoom": "min(1.12+0.0004*on,1.2)",
        "x": "iw/2-(iw/zoom/2)-on*0.55",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.07:saturation=1.1:brightness=0.02",
    },
    {
        "id": "drift_right",
        "zoom": "min(1.12+0.0004*on,1.2)",
        "x": "iw/2-(iw/zoom/2)+on*0.55",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.07:saturation=1.1:brightness=0.02",
    },
    {
        "id": "snap_zoom",
        "zoom": "if(lt(on,8),1.35-on*0.02,min(zoom+0.0009,1.16))",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.16:saturation=1.25:brightness=0.05",
    },
    {
        "id": "pull_out",
        "zoom": "max(1.28-0.0018*on,1.05)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.05:saturation=1.08",
    },
    {
        "id": "tilt_up",
        "zoom": "min(1.15+0.0003*on,1.22)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.62-(ih/zoom/2)-on*0.7",
        "eq": "eq=contrast=1.07:saturation=1.1",
    },
    {
        "id": "tilt_down",
        "zoom": "min(1.15+0.0003*on,1.22)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.38-(ih/zoom/2)+on*0.7",
        "eq": "eq=contrast=1.07:saturation=1.1",
    },
    {
        "id": "handheld",
        "zoom": "min(1.1+0.0002*on,1.16)",
        "x": "iw/2-(iw/zoom/2)+sin(on/7)*8",
        "y": "ih/2-(ih/zoom/2)+cos(on/9)*6",
        "eq": "eq=contrast=1.05:saturation=1.08",
    },
    {
        "id": "orbit",
        "zoom": "min(1.14+0.0005*on,1.22)",
        "x": "iw/2-(iw/zoom/2)+sin(on/18)*18",
        "y": "ih/2-(ih/zoom/2)+cos(on/18)*12",
        "eq": "eq=contrast=1.08:saturation=1.12",
    },
    {
        "id": "crash_zoom",
        "zoom": "if(lt(on,12),1.05+on*0.035,min(zoom+0.0008,1.35))",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.2:saturation=1.25:brightness=0.04",
    },
]

# ASS subtitle / title looks (PrimaryColour is &HAABBGGRR)
SUBTITLE_STYLES: dict[str, dict[str, str]] = {
    "classic": {
        "name": "Classic",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "0",
        "bold": "-1",
    },
    "karaoke_gold": {
        "name": "Karaoke Gold",
        "font": "Arial Black",
        "size": "82",
        "primary": "&H0000E5FF",
        "outline": "&H00000000",
        "outline_w": "7",
        "shadow": "0",
        "bold": "-1",
    },
    "box_white": {
        "name": "Box White",
        "font": "Arial",
        "size": "72",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&H99000000",
    },
    "neon_pink": {
        "name": "Neon Pink",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00FF66FF",
        "outline": "&H00FF00AA",
        "outline_w": "4",
        "shadow": "2",
        "bold": "-1",
    },
    "minimal": {
        "name": "Minimal",
        "font": "Arial",
        "size": "64",
        "primary": "&H00F0F0F0",
        "outline": "&H66000000",
        "outline_w": "2",
        "shadow": "0",
        "bold": "0",
    },
    "impact": {
        "name": "Impact",
        "font": "Impact",
        "size": "90",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "8",
        "shadow": "0",
        "bold": "-1",
    },
    "soft_shadow": {
        "name": "Soft Shadow",
        "font": "Arial",
        "size": "74",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "3",
        "shadow": "4",
        "bold": "-1",
    },
    "yellow_pop": {
        "name": "Yellow Pop",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H0000FFFF",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "0",
        "bold": "-1",
    },
    "lower_third": {
        "name": "Lower Third",
        "font": "Arial",
        "size": "58",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HC0000000",
        "align": "2",
    },
    "hook_banner": {
        "name": "Hook Banner",
        "font": "Arial Black",
        "size": "92",
        "primary": "&H0000E5FF",
        "outline": "&H00000000",
        "outline_w": "8",
        "shadow": "0",
        "bold": "-1",
    },
}

# drawtext title cards / still overlays
TEXT_STYLES: dict[str, dict[str, str]] = {
    "bold_center": {
        "fontsize": "72",
        "fontcolor": "white",
        "borderw": "5",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "(h-text_h)/2",
    },
    "hook_top": {
        "fontsize": "64",
        "fontcolor": "0xE8A54B",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.18",
    },
    "caption_bottom": {
        "fontsize": "56",
        "fontcolor": "white",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.78",
    },
    "box_lower": {
        "fontsize": "52",
        "fontcolor": "white",
        "box": "1",
        "boxcolor": "black@0.55",
        "boxborderw": "16",
        "x": "(w-text_w)/2",
        "y": "h*0.72",
    },
    "tiny_credit": {
        "fontsize": "36",
        "fontcolor": "white@0.85",
        "borderw": "2",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.92",
    },
    "mega_title": {
        "fontsize": "96",
        "fontcolor": "white",
        "borderw": "8",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "(h-text_h)/2",
    },
}

FADE_BOOKENDS = ("none", "fade", "fadeblack", "fadewhite")


def effect_chain(effect_id: str) -> str:
    return EFFECT_FILTERS.get(effect_id or "none", "") or ""


def motion_by_id(motion_id: str) -> dict[str, str] | None:
    for m in MOTION_PRESETS:
        if m["id"] == motion_id:
            return m
    return None
